<?php

namespace ComponentBundle\Repository;

use ComponentBundle\Repository\Interfaces\RepositoryInterface;
use Doctrine\ORM\Persisters\Entity\EntityPersister;

/**
 * CategoryEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryEntityRepository extends \Doctrine\ORM\EntityRepository implements RepositoryInterface
{
    public function truncate()
    {
        return $this->getEntityManager()
            ->createQuery('DELETE FROM ComponentBundle:CategoryEntity')->execute();
    }

    public function findTotalByConditions(array $criteria = []): int
    {
        /** @var EntityPersister $persister */
        $persister = $this->_em->getUnitOfWork()->getEntityPersister($this->_entityName);

        return $persister->count($criteria);
    }
}
