<?php

namespace AppBundle\Repository;

/**
 * FeedEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeedEntityRepository extends \Doctrine\ORM\EntityRepository
{
}
