<?php

namespace AppBundle\Repository;

use Doctrine\ORM\Persisters\Entity\EntityPersister;

/**
 * FeedEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeedEntityRepository extends \Doctrine\ORM\EntityRepository
{
    public function findWithLimitAndOffset(array $condtitions = [], int $limit, int $offset)
    {
        return $this->findBy($condtitions,['pubDate' => 'DESC'], $limit, $offset);
    }

    public function truncate()
    {
        return $this->getEntityManager()
            ->createQuery('DELETE FROM AppBundle:FeedEntity')->execute();
    }

    public function findCount(array $criteria = [])
    {
        /** @var EntityPersister $persister */
        $persister = $this->_em->getUnitOfWork()->getEntityPersister($this->_entityName);

        return $persister->count($criteria);
    }

    public function findAll()
    {
        return $this->findBy([],['pubDate' => 'DESC']);
    }
}
