<?php

namespace AppBundle\Repository;

/**
 * FeedEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeedEntityRepository extends \Doctrine\ORM\EntityRepository
{
    public function findWithLimitAndOffset(int $limit, int $offset)
    {
        return $this->getEntityManager()
            ->getRepository('AppBundle\Entity\FeedEntity')->findBy([],['pubDate' => 'DESC'], $limit, $offset);
    }

    public function truncate()
    {
        return $this->em->createQuery('DELETE FROM AppBundle:FeedEntity')->execute();
    }
}
