feed:
    resource: "@FeedBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

rssfeed:
    resource: "@AppBundle/Resources/config/routing.xml"
